# Generated by Django 5.1.3 on 2024-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
